version: '3.1'

services:
  arvora:
    build: src/arvora
    command: python3 -m wsgi --port=8888
    restart: always
    ports:
      - "8585:8585"

  database:
    image: tinydb:latest
    volumes:
       - tinydb-data:/var/lib/docker
volumes:
  tinydb-data:
